bash scripts/model1_full.sh &&
bash scripts/model32_full.sh &&
bash scripts/model15_full.sh &&
bash scripts/model2_full.sh &&
bash scripts/model5_synth_new_full.sh &&
bash scripts/model15_synth_tone_full.sh &&
bash scripts/model4_synth_new_full.sh &&
bash scripts/model6_new_full.sh &&
bash scripts/model2_new_full.sh &&
bash scripts/model8_synth_full.sh &&
bash scripts/model34_tone_full.sh &&
bash scripts/model13_full.sh &&
bash scripts/model20_tone_full.sh &&
bash scripts/model18_new_full.sh &&
bash scripts/model19_full.sh &&
bash scripts/model34_full.sh &&
bash scripts/model29_full.sh &&
bash scripts/model19_synth_new_full.sh &&
bash scripts/model19_synth_new_tone_full.sh &&
bash scripts/model17_full.sh &&
bash scripts/model5_new_full.sh &&
bash scripts/model17_new_full.sh &&
bash scripts/model20_full.sh &&
bash scripts/model15_synth_new_full.sh &&
bash scripts/model30_synth_full.sh &&
bash scripts/model1_synth_full.sh &&
bash scripts/model35_tone_full.sh &&
bash scripts/model19_new_full.sh &&
bash scripts/model27_full.sh &&
bash scripts/model35_full.sh &&
bash scripts/model9_full.sh &&
bash scripts/model14_full.sh &&
bash scripts/model3_new_full.sh &&
bash scripts/model30_tone_full.sh &&
bash scripts/model5_tone_full.sh &&
bash scripts/model10_synth_full.sh &&
bash scripts/model7_full.sh &&
bash scripts/model30_full.sh &&
bash scripts/model35_synth_full.sh &&
bash scripts/model31_full.sh &&
bash scripts/model26_synth_full.sh &&
bash scripts/model10_synth_new_full.sh &&
bash scripts/model15_new_full.sh &&
bash scripts/model10_full.sh &&
bash scripts/model5_synth_tone_full.sh &&
bash scripts/model33_tone_full.sh &&
bash scripts/model5_synth_full.sh &&
bash scripts/model3_tone_full.sh &&
bash scripts/model3_synth_full.sh &&
bash scripts/model5_full.sh &&
bash scripts/model4_synth_full.sh &&
bash scripts/model2_synth_full.sh